// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuNADFr88SEvr_yQEyYhPq5k6_EvW9W8',
    appId: '1:297155927144:web:15b13a437cd0b39320afdd',
    messagingSenderId: '297155927144',
    projectId: 'publifly-ai',
    authDomain: 'publifly-ai.firebaseapp.com',
    storageBucket: 'publifly-ai.firebasestorage.app',
    measurementId: 'G-4TMGY0B838',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT3pl_In767AhH4PeFipB9DyHgt3fIy30',
    appId: '1:297155927144:android:3e54e643a569b35220afdd',
    messagingSenderId: '297155927144',
    projectId: 'publifly-ai',
    storageBucket: 'publifly-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJb7ADSFDOqsrB_osBlKbrWmrUCIQxqU',
    appId: '1:297155927144:ios:72ad63912b574e3020afdd',
    messagingSenderId: '297155927144',
    projectId: 'publifly-ai',
    storageBucket: 'publifly-ai.firebasestorage.app',
    iosBundleId: 'com.example.publiflyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJb7ADSFDOqsrB_osBlKbrWmrUCIQxqU',
    appId: '1:297155927144:ios:72ad63912b574e3020afdd',
    messagingSenderId: '297155927144',
    projectId: 'publifly-ai',
    storageBucket: 'publifly-ai.firebasestorage.app',
    iosBundleId: 'com.example.publiflyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDuNADFr88SEvr_yQEyYhPq5k6_EvW9W8',
    appId: '1:297155927144:web:0ab2d7346f519f2c20afdd',
    messagingSenderId: '297155927144',
    projectId: 'publifly-ai',
    authDomain: 'publifly-ai.firebaseapp.com',
    storageBucket: 'publifly-ai.firebasestorage.app',
    measurementId: 'G-5GJWFM39S6',
  );
}
